### ISSUE TITLE
Uncaught OutOfBoundsException: Required package "symplify/easy-coding-standard" ...

### ISSUE THREAD

**Issue by miloshavlicek** [nette/coding-standard#40]
When I run CodeChecker it throws this error.

It suddenly stopped working today. I have tried to reinstall the package and run on another environment, but the error is still the same.

Could you please help me how can I solve it?

```
> composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
Creating a "nette/coding-standard" project at "temp/coding-standard"
Installing nette/coding-standard (v2.3.1)
  - Installing nette/coding-standard (v2.3.1): Downloading (100%)
Created project in /home/runner/work/mathematicator-calculator/mathematicator-calculator/temp/coding-standard
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 60 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.8.0): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.17.0): Downloading (100%)
  - Installing symfony/yaml (v5.0.8): Downloading (100%)
  - Installing psr/log (1.1.3): Downloading (100%)
  - Installing symfony/polyfill-php73 (v1.17.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.17.0): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.17.0): Downloading (100%)
  - Installing symfony/polyfill-intl-idn (v1.17.0): Downloading (100%)
  - Installing symfony/mime (v5.0.8): Downloading (100%)
  - Installing symfony/http-foundation (v5.0.8): Downloading (100%)
  - Installing psr/event-dispatcher (1.0.0): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v2.1.2): Downloading (100%)
  - Installing symfony/event-dispatcher (v5.0.8): Downloading (100%)
  - Installing symfony/var-dumper (v5.0.8): Downloading (100%)
  - Installing symfony/error-handler (v5.0.8): Downloading (100%)
  - Installing symfony/http-kernel (v5.0.8): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing psr/cache (1.0.1): Downloading (100%)
  - Installing symfony/finder (v5.0.8): Downloading (100%)
  - Installing symfony/service-contracts (v2.1.2): Downloading (100%)
  - Installing symfony/dependency-injection (v5.0.8): Downloading (100%)
  - Installing symfony/console (v5.0.8): Downloading (100%)
  - Installing symfony/filesystem (v5.0.8): Downloading (100%)
  - Installing symfony/config (v5.0.8): Downloading (100%)
  - Installing nette/utils (v3.1.2): Loading from cache
  - Installing nette/finder (v2.5.2): Loading from cache
  - Installing symplify/package-builder (v7.3.18): Downloading (100%)
  - Installing sebastian/diff (4.0.1): Downloading (100%)
  - Installing symplify/console-color-diff (v7.3.18): Downloading (100%)
  - Installing symplify/auto-bind-parameter (v7.3.18): Downloading (100%)
  - Installing symplify/parameter-name-guard (v7.3.18): Downloading (100%)
  - Installing symplify/autowire-array-parameter (v7.3.18): Downloading (100%)
  - Installing symplify/smart-file-system (v7.3.18): Downloading (100%)
  - Installing symplify/set-config-resolver (v7.3.18): Downloading (100%)
  - Installing phpstan/phpdoc-parser (0.4.4): Downloading (100%)
  - Installing symplify/coding-standard (v7.3.18): Downloading (100%)
  - Installing phpstan/phpstan (0.12.25): Loading from cache
  - Installing symfony/stopwatch (v5.0.8): Downloading (100%)
  - Installing symfony/process (v5.0.8): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.16.3): Downloading (100%)
  - Installing symplify/phpstan-extensions (v7.3.18): Downloading (100%)
  - Installing squizlabs/php_codesniffer (3.5.5): Downloading (100%)
  - Installing slevomat/coding-standard (6.3.8): Downloading (100%)
  - Installing nikic/php-parser (v4.4.0): Downloading (100%)
  - Installing symfony/var-exporter (v5.0.8): Downloading (100%)
  - Installing symfony/cache-contracts (v2.1.2): Downloading (100%)
  - Installing symfony/cache (v5.0.8): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing nette/robot-loader (v3.2.3): Downloading (100%)
  - Installing jean85/pretty-package-versions (1.3.0): Downloading (100%)
  - Installing composer/xdebug-handler (1.4.1): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.17.0): Downloading (100%)
  - Installing php-cs-fixer/diff (v1.3.0): Downloading (100%)
  - Installing doctrine/lexer (1.2.1): Downloading (100%)
  - Installing doctrine/annotations (1.10.3): Downloading (100%)
  - Installing composer/semver (1.5.1): Downloading (100%)
  - Installing symfony/options-resolver (v5.0.8): Downloading (100%)
  - Installing symplify/easy-coding-standard (v7.3.18): Downloading (100%)
  - Installing tracy/tracy (v2.7.5): Loading from cache
symfony/http-kernel suggests installing symfony/browser-kit
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/lock
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-isidenticalstring (For IsIdenticalString constraint.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-xmlmatchesxsd (For XmlMatchesXsd constraint.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
tracy/tracy suggests installing https://nette.org/donate (Please support Tracy via a donation)
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
43 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

> php temp/coding-standard/ecs check src --config temp/coding-standard/coding-standard-php71.yml
PHP Fatal error:  Uncaught OutOfBoundsException: Required package "symplify/easy-coding-standard" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files in /home/runner/work/mathematicator-calculator/mathematicator-calculator/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:101
Stack trace:
#0 /home/runner/work/mathematicator-calculator/mathematicator-calculator/temp/coding-standard/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(13): PackageVersions\Versions::getVersion()
#1 /home/runner/work/mathematicator-calculator/mathematicator-calculator/temp/coding-standard/vendor/symplify/easy-coding-standard/packages/configuration/src/Configuration.php(135): Jean85\PrettyVersions::getVersion()
#2 /home/runner/work/mathematicator-calculator/mathematicator-calculator/temp/coding-standard/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php(35): Symplify\EasyCodingStandard\Configuration\Configuration->getPrettyVersion()
#3 /tmp/easy_co in /home/runner/work/mathematicator-calculator/mathematicator-calculator/vendor/ocramius/package-versions/src/PackageVersions/Versions.php on line 101
```

**Comment by miloshavlicek** [comment]
I am sorry, this issue should be in https://github.com/nette/code-checker

**Comment by dg** [comment]
It works on my computer and on Travis too https://travis-ci.org/github/nette/application/jobs/692386641

**Comment by miloshavlicek** [comment]
@dg It seems to be a bug in Composer 2, sorry for that.
